version: '3'
services:
  database:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'rita_exam'
      MYSQL_USER: 'rita_exam'
      MYSQL_PASSWORD: 'rita_exam'
      MYSQL_ROOT_PASSWORD: 'rita_exam'
    ports:
      - '3366:3306'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql